//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.ConsumeMetroCitiesWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsumeMetroCitiesWebService.IGetMetropolitanCitiesService")]
    public interface IGetMetropolitanCitiesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetMetropolitanCitiesService/GetMetropolitanCities", ReplyAction="http://tempuri.org/IGetMetropolitanCitiesService/GetMetropolitanCitiesResponse")]
        System.Data.DataSet GetMetropolitanCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetMetropolitanCitiesService/GetMetropolitanCities", ReplyAction="http://tempuri.org/IGetMetropolitanCitiesService/GetMetropolitanCitiesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMetropolitanCitiesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetMetropolitanCitiesServiceChannel : Business.ConsumeMetroCitiesWebService.IGetMetropolitanCitiesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMetropolitanCitiesServiceClient : System.ServiceModel.ClientBase<Business.ConsumeMetroCitiesWebService.IGetMetropolitanCitiesService>, Business.ConsumeMetroCitiesWebService.IGetMetropolitanCitiesService {
        
        public GetMetropolitanCitiesServiceClient() {
        }
        
        public GetMetropolitanCitiesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetMetropolitanCitiesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetMetropolitanCitiesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetMetropolitanCitiesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetMetropolitanCities() {
            return base.Channel.GetMetropolitanCities();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMetropolitanCitiesAsync() {
            return base.Channel.GetMetropolitanCitiesAsync();
        }
    }
}
